title:             W.M.Moon
email:             wmoon5@gmail.com
description:       Some of my thoughts.
author:            wmmoon
baseurl:           ""
url:               "wmmoon.com"

# Social Profiles
twitter_username:  wmoon5
github_username:   wmoon5
facebook_username: wooyoungmoon

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate

